import { Geist, Figtree } from "next/font/google";
import "./globals.css";

const figtree = Figtree({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${figtree.className}} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          {children}
        </main>
        
        </body>
    </html>
  );
}
