import { Geist, Figtree } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";

const figtree = Figtree({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${figtree.className}} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#16112b] ">
        <Navber></Navber>
        <main>
          {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
