import { Geist, Figtree } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

const figtree = Figtree({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light" 
      className={`${figtree.className}} h-full antialiased`}
   suppressHydrationWarning >
      <body className="min-h-full flex flex-col bg-background text-foreground">   
        {/* bg-[#16112b] */}
      <Providers>
      <Toaster></Toaster>
        <Navber></Navber>
        <main>
           
          {children}
      
         
        </main>
        <Footer/>
          </Providers>
        </body>
    </html>
  );
}
